package mysql.erd.shopping;

import java.io.Serializable;

/**
 * 카트 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CartOrders implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 카드 아이디. */
	private Integer cid;

	/** 주문 테이블. */
	private OrdersOrders orders;

	/** 상품 테이블. */
	private ProductsOrders products;

	/** 수량. */
	private Integer quantity;

	/**
	 * 생성자.
	 */
	public CartOrders() {
	}

	/**
	 * 카드 아이디을 설정합니다..
	 * 
	 * @param cid
	 *            카드 아이디
	 */
	public void setCid(Integer cid) {
		this.cid = cid;
	}

	/**
	 * 카드 아이디을 가져옵니다..
	 * 
	 * @return 카드 아이디
	 */
	public Integer getCid() {
		return this.cid;
	}

	/**
	 * 주문 테이블을 설정합니다..
	 * 
	 * @param orders
	 *            주문 테이블
	 */
	public void setOrders(OrdersOrders orders) {
		this.orders = orders;
	}

	/**
	 * 주문 테이블을 가져옵니다..
	 * 
	 * @return 주문 테이블
	 */
	public OrdersOrders getOrders() {
		return this.orders;
	}

	/**
	 * 상품 테이블을 설정합니다..
	 * 
	 * @param products
	 *            상품 테이블
	 */
	public void setProducts(ProductsOrders products) {
		this.products = products;
	}

	/**
	 * 상품 테이블을 가져옵니다..
	 * 
	 * @return 상품 테이블
	 */
	public ProductsOrders getProducts() {
		return this.products;
	}

	/**
	 * 수량을 설정합니다..
	 * 
	 * @param quantity
	 *            수량
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * 수량을 가져옵니다..
	 * 
	 * @return 수량
	 */
	public Integer getQuantity() {
		return this.quantity;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cid == null) ? 0 : cid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CartOrders other = (CartOrders) obj;
		if (cid == null) {
			if (other.cid != null) {
				return false;
			}
		} else if (!cid.equals(other.cid)) {
			return false;
		}
		return true;
	}

}
