package mysql.erd.shopping;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 사용자 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Users implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 사용자 아이디. */
	private String uid;

	/** 사용자 명. */
	private String uname;

	/** tel. */
	private String tel;

	/** 주소. */
	private String addr;

	/** 주문 테이블 목록. */
	private Set<Orders> ordersSet;

	/**
	 * 생성자.
	 */
	public Users() {
		this.ordersSet = new HashSet<Orders>();
	}

	/**
	 * 사용자 아이디을 설정합니다..
	 * 
	 * @param uid
	 *            사용자 아이디
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * 사용자 아이디을 가져옵니다..
	 * 
	 * @return 사용자 아이디
	 */
	public String getUid() {
		return this.uid;
	}

	/**
	 * 사용자 명을 설정합니다..
	 * 
	 * @param uname
	 *            사용자 명
	 */
	public void setUname(String uname) {
		this.uname = uname;
	}

	/**
	 * 사용자 명을 가져옵니다..
	 * 
	 * @return 사용자 명
	 */
	public String getUname() {
		return this.uname;
	}

	/**
	 * tel을 설정합니다..
	 * 
	 * @param tel
	 *            tel
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * tel을 가져옵니다..
	 * 
	 * @return tel
	 */
	public String getTel() {
		return this.tel;
	}

	/**
	 * 주소을 설정합니다..
	 * 
	 * @param addr
	 *            주소
	 */
	public void setAddr(String addr) {
		this.addr = addr;
	}

	/**
	 * 주소을 가져옵니다..
	 * 
	 * @return 주소
	 */
	public String getAddr() {
		return this.addr;
	}

	/**
	 * 주문 테이블 목록을 설정합니다..
	 * 
	 * @param ordersSet
	 *            주문 테이블 목록
	 */
	public void setOrdersSet(Set<Orders> ordersSet) {
		this.ordersSet = ordersSet;
	}

	/**
	 * 주문 테이블를 추가합니다..
	 * 
	 * @param orders
	 *            주문 테이블
	 */
	public void addOrders(Orders orders) {
		this.ordersSet.add(orders);
	}

	/**
	 * 주문 테이블 목록을 가져옵니다..
	 * 
	 * @return 주문 테이블 목록
	 */
	public Set<Orders> getOrdersSet() {
		return this.ordersSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((uid == null) ? 0 : uid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Users other = (Users) obj;
		if (uid == null) {
			if (other.uid != null) {
				return false;
			}
		} else if (!uid.equals(other.uid)) {
			return false;
		}
		return true;
	}

}
